using System.Net;
using System.Text;
using System.Text.Json;
using UniLinker.Plugin.Sdk;

namespace UniLinker.Core;

/// <summary>
/// Minimal HTTP server for WebRTC SDP signaling exchange.
/// Each uniLinker instance runs one.
/// POST /signaling — exchange SDP offer/answer
/// GET /info — device metadata and capabilities
/// </summary>
public class SignalingServer : IDisposable
{
    private readonly HttpListener _listener;
    private readonly int _port;
    private readonly PeerMesh _peerMesh;
    private readonly string[] _capabilities;
    private CancellationTokenSource? _cts;

    public event Action<string, string>? OfferReceived; // sdp, fromPeerId
    public event Action<string>? SdpAnswerReceived;

    public SignalingServer(
        int port,
        PeerMesh peerMesh,
        string[]? capabilities = null)
    {
        _port = port;
        _peerMesh = peerMesh;
        _capabilities = capabilities ?? ["screen-capture", "h264-encode", "video-stream"];
        _listener = new HttpListener();
        _listener.Prefixes.Add($"http://+:{port}/");
    }

    public async Task StartAsync(CancellationToken ct = default)
    {
        _cts = CancellationTokenSource.CreateLinkedTokenSource(ct);

        try
        {
            _listener.Start();
        }
        catch (HttpListenerException ex) when (ex.ErrorCode == 5)
        {
            // Access denied — try with localhost only
            _listener.Prefixes.Clear();
            _listener.Prefixes.Add($"http://localhost:{_port}/");
            _listener.Prefixes.Add($"http://127.0.0.1:{_port}/");
            _listener.Start();
        }

        try
        {
            while (!_cts.IsCancellationRequested)
            {
                var ctxTask = _listener.GetContextAsync();
                using var timeoutCts = new CancellationTokenSource(TimeSpan.FromSeconds(30));
                var completedTask = await Task.WhenAny(
                    ctxTask, Task.Delay(Timeout.Infinite, timeoutCts.Token));

                if (completedTask != ctxTask || _cts.IsCancellationRequested)
                    break;

                var ctx = await ctxTask;
                _ = HandleRequestAsync(ctx);
            }
        }
        catch (OperationCanceledException) { }
        catch (HttpListenerException) { /* shutting down */ }
    }

    private async Task HandleRequestAsync(HttpListenerContext ctx)
    {
        try
        {
            var path = ctx.Request.Url?.AbsolutePath ?? "/";

            switch (path)
            {
                case "/info":
                    await SendJson(ctx, new
                    {
                        name = Environment.MachineName,
                        version = "3.0.0",
                        capabilities = _capabilities,
                        status = "available",
                    });
                    break;

                case "/signaling" when ctx.Request.HttpMethod == "POST":
                    await HandleSignaling(ctx);
                    break;

                default:
                    ctx.Response.StatusCode = 404;
                    ctx.Response.Close();
                    break;
            }
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"Signaling error: {ex.Message}");
            try
            {
                ctx.Response.StatusCode = 500;
                ctx.Response.Close();
            }
            catch { /* best effort */ }
        }
    }

    private async Task HandleSignaling(HttpListenerContext ctx)
    {
        using var reader = new StreamReader(ctx.Request.InputStream, Encoding.UTF8);
        var body = await reader.ReadToEndAsync();

        var msg = JsonSerializer.Deserialize<SignalingMessage>(body);
        if (msg == null)
        {
            ctx.Response.StatusCode = 400;
            ctx.Response.Close();
            return;
        }

        if (msg.Type == "offer")
        {
            OfferReceived?.Invoke(msg.Sdp, msg.FromPeerId);

            // The actual answer will be generated by the peer manager
            // For now, echo a basic answer
            var answer = new SignalingMessage
            {
                Type = "answer",
                Sdp = "v=0\r\no=- 0 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\n",
                FromPeerId = Environment.MachineName,
            };
            await SendJson(ctx, answer);
        }
        else if (msg.Type == "answer")
        {
            SdpAnswerReceived?.Invoke(msg.Sdp);
            ctx.Response.StatusCode = 200;
            ctx.Response.Close();
        }
        else
        {
            ctx.Response.StatusCode = 400;
            ctx.Response.Close();
        }
    }

    private static async Task SendJson(HttpListenerContext ctx, object data)
    {
        var json = JsonSerializer.Serialize(data, new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        });
        var buf = Encoding.UTF8.GetBytes(json);

        ctx.Response.ContentType = "application/json";
        ctx.Response.ContentLength64 = buf.Length;
        await ctx.Response.OutputStream.WriteAsync(buf);
        ctx.Response.Close();
    }

    public void Stop()
    {
        _cts?.Cancel();
        try { _listener.Stop(); } catch { }
    }

    public void Dispose()
    {
        _cts?.Cancel();
        _cts?.Dispose();
        try { (_listener as IDisposable)?.Dispose(); } catch { }
    }
}

public class SignalingMessage
{
    public string Type { get; set; } = ""; // "offer" or "answer"
    public string Sdp { get; set; } = "";
    public string FromPeerId { get; set; } = "";
    public string? Capability { get; set; }
}
